#!/bin/bash

INSTALL_DIR=$(python3 -c 'import sysconfig;print(sysconfig.get_paths().get("platlib"))')

bin='./funpackager/bin/funpackager'

BIN_DIR="$1"
if [[ -z "$1" ]]; then
  BIN_DIR=~/bin/funpackager
fi

sudo cp -apv $bin $BIN_DIR && cp -vr ./funpackager $INSTALL_DIR
